# Generated by Django 4.2.24 on 2025-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='document_number',
            field=models.CharField(default='TEMP000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(default='Sin nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='therapist',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name_maternal',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name_paternal',
            field=models.CharField(default='Sin apellido', max_length=150),
        ),
        migrations.AddField(
            model_name='therapist',
            name='personal_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
