# Generated by Django 5.2.6 on 2025-09-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_district_documenttype_province_region_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN phone_number VARCHAR(20);",
            reverse_sql="ALTER TABLE patients DROP COLUMN phone_number;"
        ),
    ]
