# Generated by Django 5.2.6 on 2025-09-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20250915_1728'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN document_number VARCHAR(20) DEFAULT 'TEMP000';",
            reverse_sql="ALTER TABLE patients DROP COLUMN document_number;"
        ),
    ]
