# Generated by Django 5.2.6 on 2025-09-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20250915_1730'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN ocupation VARCHAR(100) DEFAULT 'Sin especificar';",
            reverse_sql="ALTER TABLE patients DROP COLUMN ocupation;"
        ),
    ]
