# Generated by Django 5.2.6 on 2025-09-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_auto_20250915_1732'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN health_condition TEXT DEFAULT 'Sin especificar';",
            reverse_sql="ALTER TABLE patients DROP COLUMN health_condition;"
        ),
    ]
