# Generated by Django 5.2.6 on 2025-09-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20250915_1734'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE patients DROP COLUMN created_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE patients ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE patients DROP COLUMN updated_at;"
        ),
    ]
