# Generated by Django 5.2.6 on 2025-09-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20250915_1737'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE patients 
            ADD COLUMN document_type_id BIGINT DEFAULT 1,
            ADD COLUMN district_id BIGINT DEFAULT 1,
            ADD COLUMN province_id BIGINT DEFAULT 1,
            ADD COLUMN region_id BIGINT DEFAULT 1;
            """,
            reverse_sql="""
            ALTER TABLE patients 
            DROP COLUMN document_type_id,
            DROP COLUMN district_id,
            DROP COLUMN province_id,
            DROP COLUMN region_id;
            """
        ),
    ]
