# Generated by Django 5.2.6 on 2025-09-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20250915_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
